title: An R Tool for the Luria-Delbruck Fluctuation Assay
description: "rSalvador: An R Tool for the Luria-Delbruck Fluctuation Assay"
google_analytics: 
show_downloads: true
theme: jekyll-theme-midnight

gems:
  - jekyll-mentions
