name: r-salvador
services:
  - name: websalvador
    github:
      repo: eeeeeric/rSalvador
      branch: digitalocean
      deploy_on_push: true
    dockerfile_path: websalvador/Dockerfile
    source_dir: websalvador
